
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  kubeProxyMode: "ipvs"
nodes:
- role: control-plane
  labels:
    ingress-ready: "true"
  kubeadmConfigPatches:
  - |
    kind: KubeProxyConfiguration
    ipvs:
      strictARP: true
  extraPortMappings:
  - containerPort: 8020
    hostPort: 8020
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
  labels:
    ingress-ready: "true"
  kubeadmConfigPatches:
  - |
    kind: KubeProxyConfiguration
    ipvs:
      strictARP: true
  extraPortMappings:
  - containerPort: 8020
    hostPort: 81
    protocol: TCP
  - containerPort: 443
    hostPort: 4431
    protocol: TCP
- role: worker
  labels:
    ingress-ready: "true"
  kubeadmConfigPatches:
  - |
    kind: KubeProxyConfiguration
    ipvs:
      strictARP: true
  extraPortMappings:
  - containerPort: 8020
    hostPort: 82
    protocol: TCP
  - containerPort: 443
    hostPort: 4432
    protocol: TCP